*

!Dockerfile
!Dockerfile.dockerignore
!package.json
!package-lock.json
!tsconfig.json
!src/
!src/**
!packages/audit-sdk/package.json
!packages/audit-sdk/tsconfig.json
!packages/audit-sdk/src/
!packages/audit-sdk/src/**
!packages/audit-sdk/contract/
!packages/audit-sdk/contract/**
