#!/usr/bin/env bash

set -euo pipefail

AI_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$AI_DIR")"
RULES_DIR="$AI_DIR/rules"
SKILLS_DIR="$AI_DIR/skills"
REVIEW_AGENTS_DIR="$AI_DIR/agents"
META_DIR="$AI_DIR/meta"
MANAGED_OUTPUTS_FILE="$AI_DIR/generated-outputs.txt"
MANAGED_OUTPUTS_TMP="$(mktemp "$AI_DIR/.generated-outputs.XXXXXX")"

trap 'rm -f -- "$MANAGED_OUTPUTS_TMP"' EXIT

GENERATED_HEADER="<!-- Generated by .ai/sync.sh. Edit files in .ai/ and re-run sync.sh. -->"
GENERATED_TOML_HEADER="# Generated by .ai/sync.sh. Edit files in .ai/ and re-run sync.sh."

log() {
  echo "  $*"
}

section() {
  echo
  echo "▶ $*"
}

read_meta() {
  local file="$1"
  local key="$2"

  grep -E "^${key}:" "$file" 2>/dev/null \
    | head -1 \
    | sed -E "s/^${key}:[[:space:]]*[\"']?([^\"']*)[\"']?[[:space:]]*/\1/"
}

read_agent_meta() {
  local file="$1"
  local key="$2"

  awk -v key="$key" '
    NR == 1 && $0 == "---" { in_meta = 1; next }
    in_meta && $0 == "---" { exit }
    in_meta && index($0, key ":") == 1 {
      sub("^[^:]+:[[:space:]]*", "")
      print
      exit
    }
  ' "$file" \
    | sed -E "s/^[[:space:]]*//; s/[[:space:]]*$//; s/^[\"']//; s/[\"']$//"
}

agent_body() {
  local file="$1"

  awk '
    NR == 1 && $0 == "---" { in_meta = 1; next }
    in_meta && $0 == "---" { in_body = 1; next }
    in_body { print }
  ' "$file"
}

codex_agent_name() {
  local file="$1"
  local name

  name="$(read_agent_meta "$file" "codexName")"
  if [ -z "$name" ]; then
    name="$(read_agent_meta "$file" "name" | tr '-' '_')"
  fi
  echo "$name"
}

write_codex_agent() {
  local source_file="$1"
  local output_file="$2"
  local name
  local description
  local model
  local reasoning_effort
  local sandbox_mode
  local nicknames

  name="$(codex_agent_name "$source_file")"
  description="$(read_agent_meta "$source_file" "description")"
  model="$(read_agent_meta "$source_file" "codexModel")"
  reasoning_effort="$(read_agent_meta "$source_file" "codexReasoningEffort")"
  sandbox_mode="$(read_agent_meta "$source_file" "sandboxMode")"
  nicknames="$(read_agent_meta "$source_file" "nicknames")"

  [ -n "$model" ] || model="gpt-5.4"
  [ -n "$reasoning_effort" ] || reasoning_effort="high"
  [ -n "$sandbox_mode" ] || sandbox_mode="read-only"
  [ -n "$nicknames" ] || nicknames="[]"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "$GENERATED_TOML_HEADER"
    echo "name = \"${name}\""
    echo "description = \"${description}\""
    echo "model = \"${model}\""
    echo "model_reasoning_effort = \"${reasoning_effort}\""
    echo "sandbox_mode = \"${sandbox_mode}\""
    echo "nickname_candidates = ${nicknames}"
    echo "developer_instructions = \"\"\""
    agent_body "$source_file"
    echo "\"\"\""
  } > "$output_file"
}

write_claude_agent() {
  local source_file="$1"
  local output_file="$2"
  local name
  local description

  name="$(read_agent_meta "$source_file" "name")"
  description="$(read_agent_meta "$source_file" "description")"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "---"
    echo "name: ${name}"
    echo "description: ${description}"
    echo "tools: Read, Grep, Glob"
    echo "model: inherit"
    echo "---"
    echo
    echo "$GENERATED_HEADER"
    echo
    agent_body "$source_file"
  } > "$output_file"
}

write_gemini_agent() {
  local source_file="$1"
  local output_file="$2"
  local name
  local description

  name="$(read_agent_meta "$source_file" "name")"
  description="$(read_agent_meta "$source_file" "description")"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "---"
    echo "name: ${name}"
    echo "description: ${description}"
    echo "kind: local"
    echo "tools:"
    echo "  - read_file"
    echo "  - grep_search"
    echo "model: inherit"
    echo "temperature: 0.2"
    echo "max_turns: 30"
    echo "---"
    echo
    echo "$GENERATED_HEADER"
    echo
    agent_body "$source_file"
  } > "$output_file"
}

write_cursor_agent() {
  local source_file="$1"
  local output_file="$2"
  local name
  local description

  name="$(read_agent_meta "$source_file" "name")"
  description="$(read_agent_meta "$source_file" "description")"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "---"
    echo "name: ${name}"
    echo "description: ${description}"
    echo "---"
    echo
    echo "$GENERATED_HEADER"
    echo
    agent_body "$source_file"
  } > "$output_file"
}

build_index() {
  echo "$GENERATED_HEADER"
  echo

  if [ -f "$AI_DIR/project-guidance.md" ]; then
    cat "$AI_DIR/project-guidance.md"
    echo
    echo "---"
    echo
  fi

  echo "## AI Rules"
  echo
  echo "Apply rules marked **always-on** throughout. Read other rule files from \`.ai/rules/\` when the task matches their description."
  echo

  for rule_file in "$RULES_DIR"/*.md; do
    [ -f "$rule_file" ] || continue
    local name
    local meta_file
    local description
    local always_apply
    name="$(basename "$rule_file" .md)"
    meta_file="$META_DIR/${name}.yaml"
    description="Repository-specific rule"
    always_apply="false"
    if [ -f "$meta_file" ]; then
      description="$(read_meta "$meta_file" "description")"
      always_apply="$(read_meta "$meta_file" "alwaysApply")"
    fi
    if [ "$always_apply" = "true" ]; then
      echo "- **${name}** — **Always-on:** ${description} (read \`.ai/rules/${name}.md\`)"
    else
      echo "- **${name}**: ${description} (read \`.ai/rules/${name}.md\`)"
    fi
  done

  echo
  echo "## AI Skills"
  echo
  echo "Read the relevant skill file from \`.ai/skills/\` when the task matches its description."
  echo

  for skill_path in "$SKILLS_DIR"/*; do
    [ -d "$skill_path" ] || continue
    local name
    local meta_file
    local description
    name="$(basename "$skill_path")"
    meta_file="$META_DIR/${name}.yaml"
    description="Repository-specific skill"
    if [ -f "$meta_file" ]; then
      description="$(read_meta "$meta_file" "description")"
    fi
    echo "- **${name}**: ${description} (read \`.ai/skills/${name}/SKILL.md\`)"
  done

  echo
  echo "## AI Review Agents"
  echo
  echo "Reusable review subagent definitions live in \`.ai/agents/\` and are generated into the platform-specific agent formats by \`.ai/sync.sh\`."
  echo

  for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    local name
    local description
    name="$(read_agent_meta "$agent_file" "name")"
    description="$(read_agent_meta "$agent_file" "description")"
    echo "- **${name}**: ${description} (source: \`.ai/agents/$(basename "$agent_file")\`)"
  done
}

write_with_header() {
  local source_file="$1"
  local output_file="$2"

  mkdir -p "$(dirname "$output_file")"
  {
    echo "$GENERATED_HEADER"
    echo
    cat "$source_file"
  } > "$output_file"
}

copy_skill_dir() {
  local skill_dir="$1"
  local output_dir="$2"

  mkdir -p "$output_dir"
  cp -R "$skill_dir"/. "$output_dir"/
}

write_managed_outputs() {
  echo "# Generated by .ai/sync.sh. Edit canonical .ai content and re-run sync.sh."
  echo "# Paths are relative to the repository root."

  for rule_file in "$RULES_DIR"/*.md; do
    [ -f "$rule_file" ] || continue
    name="$(basename "$rule_file" .md)"
    echo ".cursor/rules/${name}.mdc"
    echo ".roo/rules/${name}.md"
    echo ".codex/rules/${name}.md"
    echo ".claude/rules/${name}.md"
    echo ".gemini/rules/${name}.md"
  done

  for skill_path in "$SKILLS_DIR"/*; do
    [ -d "$skill_path" ] || continue
    name="$(basename "$skill_path")"
    meta_file="$META_DIR/${name}.yaml"
    skill_name="$name"
    if [ -f "$meta_file" ]; then
      skill_name_meta="$(read_meta "$meta_file" "skillName")"
      [ -n "$skill_name_meta" ] && skill_name="$skill_name_meta"
    fi
    echo ".cursor/skills/${skill_name}"
    echo ".roo/skills/${name}"
    echo ".codex/skills/${name}"
    echo ".claude/skills/${name}"
    echo ".gemini/skills/${name}"
  done

  for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
    [ -f "$agent_file" ] || continue
    name="$(read_agent_meta "$agent_file" "name")"
    echo ".cursor/agents/${name}.md"
    echo ".codex/agents/${name}.toml"
    echo ".claude/agents/${name}.md"
    echo ".gemini/agents/${name}.md"
  done

  echo ".codex/AGENTS.md"
  echo ".claude/CLAUDE.md"
  echo ".gemini/GEMINI.md"
  echo "AGENTS.md"
}

is_managed_output_path() {
  local relative_path="$1"

  case "$relative_path" in
    /* | *..*) return 1 ;;
  esac

  case "$relative_path" in
    AGENTS.md | \
      .cursor/rules/*.mdc | .cursor/skills/* | .cursor/agents/*.md | \
      .roo/rules/*.md | .roo/skills/* | \
      .codex/AGENTS.md | .codex/rules/*.md | .codex/skills/* | .codex/agents/*.toml | \
      .claude/CLAUDE.md | .claude/rules/*.md | .claude/skills/* | .claude/agents/*.md | \
      .gemini/GEMINI.md | .gemini/rules/*.md | .gemini/skills/* | .gemini/agents/*.md)
      return 0
      ;;
    *) return 1 ;;
  esac
}

clean_managed_outputs() {
  if [ -z "$ROOT_DIR" ] || [ "$ROOT_DIR" = "/" ]; then
    echo "Refusing to clean generated outputs for unsafe ROOT_DIR: $ROOT_DIR" >&2
    exit 1
  fi

  [ -f "$MANAGED_OUTPUTS_FILE" ] || return 0

  while IFS= read -r relative_path; do
    case "$relative_path" in
      "" | \#*) continue ;;
    esac
    if ! is_managed_output_path "$relative_path"; then
      echo "Refusing unsafe generated-output path: $relative_path" >&2
      exit 1
    fi
    rm -rf -- "$ROOT_DIR/$relative_path"
  done < "$MANAGED_OUTPUTS_FILE"
}

write_managed_outputs > "$MANAGED_OUTPUTS_TMP"
clean_managed_outputs
mv "$MANAGED_OUTPUTS_TMP" "$MANAGED_OUTPUTS_FILE"

section "Cursor"

mkdir -p "$ROOT_DIR/.cursor/rules" "$ROOT_DIR/.cursor/skills" "$ROOT_DIR/.cursor/agents"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  meta_file="$META_DIR/${name}.yaml"
  description="Repository-specific rule"
  always_apply="false"

  if [ -f "$meta_file" ]; then
    description="$(read_meta "$meta_file" "description")"
    always_apply="$(read_meta "$meta_file" "alwaysApply")"
    [ -z "$always_apply" ] && always_apply="false"
  fi

  out="$ROOT_DIR/.cursor/rules/${name}.mdc"
  {
    echo "$GENERATED_HEADER"
    echo "---"
    echo "description: ${description}"
    echo "alwaysApply: ${always_apply}"
    echo "---"
    cat "$rule_file"
  } > "$out"
  log "OK    .cursor/rules/${name}.mdc"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  meta_file="$META_DIR/${name}.yaml"
  skill_name="$name"

  if [ -f "$meta_file" ]; then
    skill_name_meta="$(read_meta "$meta_file" "skillName")"
    [ -n "$skill_name_meta" ] && skill_name="$skill_name_meta"
  fi

  copy_skill_dir "$skill_path" "$ROOT_DIR/.cursor/skills/${skill_name}"
  log "OK    .cursor/skills/${skill_name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_cursor_agent "$agent_file" "$ROOT_DIR/.cursor/agents/${name}.md"
  log "OK    .cursor/agents/${name}.md"
done

section "Roo"

mkdir -p "$ROOT_DIR/.roo/rules" "$ROOT_DIR/.roo/skills"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.roo/rules/${name}.md"
  log "OK    .roo/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.roo/skills/${name}"
  log "OK    .roo/skills/${name}"
done

section "Codex"

mkdir -p "$ROOT_DIR/.codex/skills" "$ROOT_DIR/.codex/rules" "$ROOT_DIR/.codex/agents"
build_index > "$ROOT_DIR/.codex/AGENTS.md"
build_index > "$ROOT_DIR/AGENTS.md"
log "OK    .codex/AGENTS.md"
log "OK    AGENTS.md"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.codex/rules/${name}.md"
  log "OK    .codex/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.codex/skills/${name}"
  log "OK    .codex/skills/${name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_codex_agent "$agent_file" "$ROOT_DIR/.codex/agents/${name}.toml"
  log "OK    .codex/agents/${name}.toml"
done

section "Claude"

mkdir -p "$ROOT_DIR/.claude/skills" "$ROOT_DIR/.claude/rules" "$ROOT_DIR/.claude/agents"
build_index > "$ROOT_DIR/.claude/CLAUDE.md"
log "OK    .claude/CLAUDE.md"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.claude/rules/${name}.md"
  log "OK    .claude/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.claude/skills/${name}"
  log "OK    .claude/skills/${name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_claude_agent "$agent_file" "$ROOT_DIR/.claude/agents/${name}.md"
  log "OK    .claude/agents/${name}.md"
done

section "Gemini"

mkdir -p "$ROOT_DIR/.gemini/skills" "$ROOT_DIR/.gemini/rules" "$ROOT_DIR/.gemini/agents"
build_index > "$ROOT_DIR/.gemini/GEMINI.md"
log "OK    .gemini/GEMINI.md"

for rule_file in "$RULES_DIR"/*.md; do
  [ -f "$rule_file" ] || continue
  name="$(basename "$rule_file" .md)"
  write_with_header "$rule_file" "$ROOT_DIR/.gemini/rules/${name}.md"
  log "OK    .gemini/rules/${name}.md"
done

for skill_path in "$SKILLS_DIR"/*; do
  [ -d "$skill_path" ] || continue
  name="$(basename "$skill_path")"
  copy_skill_dir "$skill_path" "$ROOT_DIR/.gemini/skills/${name}"
  log "OK    .gemini/skills/${name}"
done

for agent_file in "$REVIEW_AGENTS_DIR"/*.md; do
  [ -f "$agent_file" ] || continue
  name="$(read_agent_meta "$agent_file" "name")"
  write_gemini_agent "$agent_file" "$ROOT_DIR/.gemini/agents/${name}.md"
  log "OK    .gemini/agents/${name}.md"
done

echo
echo "Done."
